### ISSUE TITLE
공지사항 페이지 틀 만들기, 공지사항 DB 띄우기

### ISSUE THREAD

**Issue by JEONGYOUNGYUN** [JEONGYOUNGYUN/Cashbook_Project406#12]
공지사항 페이지 틀 만들기, 공지사항 db 띄우기 하면서 세부적으로 해야 하는 것들 밑에 적어주세요

**Comment by hannammulminam** [comment]
이번 주 한일 
- 빈 에러 ServiceImpl에 @Autowired 옆에 (required = false)붙여 해결
- 빈 에러를 고친 후 service, controller, mapper, sql, jsp를 만들어 공지사항 관련 파일을 만들어 연계 후 서버를 작동하여 페이지에 들어가면
-  경로 []의 컨텍스트 내의 서블릿 [appServlet]을(를) 위한 Servlet.service() 호출이, 근본 원인(root cause)과 함께, 예외 [Request processing failed; nested exception is java.lang.NullPointerException]을(를) 발생시켰습니다.
java.lang.NullPointerException
라는 에러가 뜸.

**Comment by dalangu** [comment]
- Bean생성 오류로 파악되어 Spring 환경설정 확인 결과 web.xml에서 root-context.xml경로가 주석 처리 된 것을 발견 후 주석 해제 후 정상 작동 확인.

- 2/20 월요일 회의를 통해 팀원들에게 공유
